#!/usr/bin/env python3
"""
emit_overrides.py — bridge BLS pipeline output → app price overrides.

Reads:    data/processed/bls_prices.json  (produced by build_all.py)
Writes:   src/data/blsOverrides.js        (consumed by src/data/foods.js)

The mapping below pairs BLS item names (the raw "Bananas, per lb" strings
from ap.item) with our app's food ids. It is hand-curated because BLS
items don't share a numeric key with USDA Foundation Foods. If you add
foods to FOODS, add their BLS counterparts here.

We also write per-serving prices, not per-pound. SERVINGS_PER_LB tells the
emitter how many of OUR servings fit in 1 BLS pound (e.g., a 4 oz chicken
serving = 4 servings/lb; an "1 oz" almond serving = 16 servings/lb).
"""

import os
import json
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
IN_PATH  = os.path.join(HERE, '..', 'processed', 'bls_prices.json')
OUT_PATH = os.path.join(HERE, '..', '..', 'src', 'data', 'blsOverrides.js')

# (food_id, bls_item_substring, servings_per_lb)
# `servings_per_lb` reflects the food record's `unit` field in foods.js.
MAPPING = [
    # POULTRY
    (1,  'chicken breast',                    4),    # 4 oz
    (4,  'chicken, fresh, whole',             4),    # 4 oz
    # BEEF & PORK
    (10, 'ground chuck, 100% beef',           4),    # 4 oz, 90/10 ~ chuck
    (11, 'ground beef, 100% beef',            4),    # 4 oz, 80/20
    (14, 'pork chops',                        4),
    # FISH
    (20, 'tuna, light, chunk',                5.33),  # 3 oz can
    (24, 'salmon',                            4),
    # EGGS
    (30, 'eggs, grade a, large',              8),    # 2 large eggs ~ 4 oz; 1lb = 8 servings
    # DAIRY
    (42, 'milk, fresh, whole, fortified',     2),    # 1 cup ~ 8 oz; per-gallon→per-cup needs unit conv
    (43, 'milk, fresh, lowfat',               2),
    (44, 'cheddar cheese',                   16),    # 1 oz
    # GRAINS
    (61, 'rice, white, long grain',          16),    # ½ cup cooked ~ 1 oz dry
    (62, 'rice, white, long grain, uncooked',16),
    (66, 'bread, white, pan',                 8),    # 2 slices ~ 2 oz
    (90, 'bananas',                           4),    # 1 medium ~ 4 oz
    (91, 'apples, red delicious',             3),
    (93, 'oranges, navel',                    3),
    (74, 'potatoes',                          3),    # carrots → no direct BLS series, fallback
    (65, 'potatoes, white',                   3),
]


def main():
    if not os.path.exists(IN_PATH):
        print(f'  ⚠  {IN_PATH} not found. Run `python build_all.py` first.')
        print(f'  Skipping override generation; foods.js will use hand-curated prices.')
        return

    with open(IN_PATH) as f:
        bls = json.load(f)

    # Index BLS items by lowercased name → record.
    by_name = {r['item'].lower(): r for r in bls}

    overrides = {}  # food_id → { region: per_serving_price }

    for food_id, needle, srvs_per_lb in MAPPING:
        match = next((r for k, r in by_name.items() if needle in k), None)
        if not match:
            continue
        per_food = {}
        for region in ('us', 'ne', 'mw', 'so', 'we'):
            lb_price = match.get(region)
            if lb_price is None or srvs_per_lb <= 0:
                continue
            per_food[region] = round(lb_price / srvs_per_lb, 3)
        if per_food:
            overrides[food_id] = per_food

    # Emit the JS file.
    body = json.dumps(overrides, indent=2, sort_keys=True)
    js = (
        '// AUTO-GENERATED by data/pipeline/emit_overrides.py — do not edit by hand.\n'
        '// Re-generate with:  python data/pipeline/emit_overrides.py\n'
        '\n'
        f'export const BLS_OVERRIDES = {body};\n'
    )
    with open(OUT_PATH, 'w') as f:
        f.write(js)

    print(f'  ✓ Wrote {len(overrides)} food overrides → {OUT_PATH}')
    matched = [r for k, r in by_name.items() for fid, n, _ in MAPPING if n in k]
    print(f'    matched {len({id(r) for r in matched})} BLS items from {len(MAPPING)} mappings')


if __name__ == '__main__':
    main()
